diff --git a/Makefile.in b/Makefile.in
index bbbef5ee..26d45972 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -671,6 +671,16 @@ $(OBJ)/.vkd3d-proton-post-build64:
 	touch $@
 
 
+##
+## LatencyFleX2
+##
+$(OBJ)/.vkd3d-proton-post-build32:
+	mkdir -p "$(DST_DIR)"/lib/wine/lfx2
+	cp $(SRCDIR)/lfx2-bin/latencyflex2_rust_32.dll "$(DST_DIR)"/lib/wine/lfx2/latencyflex2_rust.dll
+
+$(OBJ)/.vkd3d-proton-post-build64:
+	mkdir -p "$(DST_DIR)"/lib64/wine/lfx2
+	cp $(SRCDIR)/lfx2-bin/latencyflex2_rust.dll "$(DST_DIR)"/lib64/wine/lfx2
 
 ##
 ## BattlEye Bridge
